"""add language to posts

Revision ID: 645e67f205a8
Revises: 5100404411d0
Create Date: 2019-10-02 17:04:34.845813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645e67f205a8'
down_revision = '5100404411d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
